fix bug

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -50,8 +50,9 @@ runs:
       - name: Run the Kurtosis package
         run: |
           TRIMMED_PATH="${PATH//\/usr\/bin:/}"
-          ENCLAVE_NAME="${GITHUB_REF_NAME//\//-}"
-          kurtosis enclave rm ${ENCLAVE_NAME} -f || echo "Couldn't delete perhaps first run"
+          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
+          ENCLAVE_NAME="${BRANCH_NAME//\//-}"
+          kurtosis enclave rm ${ENCLAVE_NAME} -f 2>/dev/null || echo "Couldn't delete perhaps first run"
           if [ -n "${ARGS_FILE}" ]; then
             kurtosis run $GITHUB_WORKSPACE/${TRIMMED_PATH} --args-file ${ARGS_FILE} --enclave ${ENCLAVE_NAME} | tee kurtosis_output.txt
           else
@@ -65,29 +66,25 @@ runs:
         if: inputs.cloud_instance_id != '' && inputs.cloud_api_key != ''
         run: |
           KURTOSIS_OUTPUT="$(cat kurtosis_output.txt)"
-          
-          echo "$KURTOSIS_OUTPUT"
 
-          # Extract Enclave UUID
+          # Extract the Enclave UUID
           ENCLAVE_UUID=$(echo "$KURTOSIS_OUTPUT" | grep 'UUID:' | head -n 1 | awk '{print $2}')
 
-          # Extract Service UUIDs for services with an HTTP port
-          SERVICE_UUIDS=$(echo "$KURTOSIS_OUTPUT" | grep 'http:' | awk '{print $1}')
+          # Loop through each service line that contains an HTTP port
+          echo "$KURTOSIS_OUTPUT" | grep 'http:' | while read -r service_line; do
+              # Extract the Service UUID
+              SERVICE_UUID=$(echo "$service_line" | awk '{print $1}')
 
-          # Extract the first 12 characters of the cloud instance ID
-          INSTANCE_ID_PREFIX=$(echo "${{ inputs.cloud_instance_id }}" | cut -c 1-12)
+              # Extract the actual port number mapped to 80
+              PORT_MAPPING=$(echo "$service_line" | grep -o 'http: [0-9]\+/tcp -> http://127.0.0.1:[0-9]\+' | sed -E 's/http: ([0-9]+)\/tcp -> http:\/\/127.0.0.1:([0-9]+)/\2/')
 
-          # For each service, generate the link
-          echo "$SERVICE_UUIDS" | while read -r SERVICE_UUID; do
-            if [[ ! -z "$SERVICE_UUID" ]]; then
-              # Extract the port number
-              PORT_NUMBER=$(echo "$KURTOSIS_OUTPUT" | grep "$SERVICE_UUID" | grep 'http:' | awk '{print $4}' | cut -d':' -f2 | cut -d'/' -f1)
-              
+              # Extract the first 12 characters of the cloud instance ID
+              INSTANCE_ID_PREFIX=$(echo "${{ inputs.cloud_instance_id }}" | cut -c 1-12)
+
               # Construct the URL
-              URL="https://${PORT_NUMBER}-${SERVICE_UUID}-${ENCLAVE_UUID}-${INSTANCE_ID_PREFIX}.cloud.kurtosis.com/"
-              
+              URL="https://${PORT_MAPPING}-${SERVICE_UUID}-${ENCLAVE_UUID}-${INSTANCE_ID_PREFIX}.cloud.kurtosis.com/"
+
               echo "Service URL: $URL"
-            fi
           done
         shell: bash
         env:
